import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import { MagnifyingGlassIcon, MicrophoneIcon } from '@heroicons/react/24/solid';
import Footer from '../components/Footer';
import Body from '../components/Body';

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Body />
      <Footer />
    </>
  );
}
